name: Provision and Deploy

on:
  push:
    branches:
      - feature/my-change-updated
    tags:
      - 'deploy-*'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ap-south-1
      PEM_KEY: ${{ secrets.PEM_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.5

      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve

      - name: Save PEM file
        run: |
          echo "${PEM_KEY}" > mykey.pem
          chmod 600 mykey.pem

      - name: Run Deploy Script
        working-directory: script
        run: bash deploy2.sh
