name: Deploy Infrastructure and Run Script

on:
  push:
    branches:
      - feature/my-change-updated
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.9.5

      # 3. Terraform Init
      - name: Terraform Init
        working-directory: terraform
        run: terraform init

      # 4. Terraform Apply
      - name: Terraform Apply
        working-directory: terraform
        run: terraform apply -auto-approve -var="bucket_name=my-private-bucket-12345"

      # 5. Run deploy2.sh
      - name: Run deploy script
        working-directory: scripts
        run: chmod +x deploy2.sh && ./deploy2.sh
